### ISSUE TITLE
ids are int64 in the lib but it's uint64 in Shopify

### ISSUE THREAD

**Issue by ttyfky** [bold-commerce/go-shopify#106]
According to public doc of Shopify [1], ProductID is unsigned int 64, however, Product in the lib has int64 [2]. This diff would be not only in Product but the other models as well.
This can be critical difference once the value exceeds range of int64. (although not sure how it is realistically exceeded)

[1] https://shopify.dev/docs/admin-api/rest/reference/products/product?api[version]=2020-01
> An unsigned 64-bit integer that's used as a unique identifier for the product. Each id is unique across the Shopify system. No two products will have the same id, even if they're from different shops.

[2] https://github.com/bold-commerce/go-shopify/blob/master/product.go#L43

**Comment by oliver006** [comment]
This is a good candidate for upcoming breakingchanges release due to #5

**Comment by oliver006** [comment]
Tackling this in #258

**Comment by oliver006** [comment]
[v4.0.0](https://github.com/bold-commerce/go-shopify/releases/tag/v4.0.0) was released - this should be fixed.
