### ISSUE TITLE
Product.ListWithPagination Broken

### ISSUE THREAD

**Issue by achempak** [bold-commerce/go-shopify#107]
I am trying to grab all of my products from Shopify, which number over 200. When I attempt to use `ListWithPagination`, the `NextPageOptions` and `PrevPageOptions` are both `nil`. In particular, I have
```
        var prodList [][]goshopify.Product
	ops := interface{}(goshopify.ProductListOptions{
		ListOptions: goshopify.ListOptions{
			Page:  1,
			Limit: 50,
		},
	})
	for true {
		 prods, page, err := client.Product.ListWithPagination(ops)
                 check(err)
		prodList = append(prodList, prods)
		 if page.NextPageOptions == nil {
		 	break
		 }
		 ops = interface{}(page.NextPageOptions)
	}
```
Using a debugger, I find that `page` only contains `nil` values, and the loop breaks immediately. I currently get around this situation by using `Product.List` and iterating until it returns an empty `Product` slice, although I don't know how safe this is. I have
```
        var prodList [][]goshopify.Product
	ops := goshopify.ProductListOptions{
		ListOptions: goshopify.ListOptions{
			Page:  1,
			Limit: 50,
		},
	}
	for true {
		prods, err := client.Product.List(ops)
		check(err)
		prodList = append(prodList, prods)
		if len(prods) == 0 {
			break
		}
		ops.ListOptions.Page++
	}
```
This does work and pulls all products from Shopify.

**Comment by brendankay** [comment]
The `Page` option is no longer used by pagination as you cannot request a specific page, instead you can only make the initial request and iterate through the results.

It seems like a long shot but can you try removing `Page` and see if that works.
The rest of the pagination code looks sound.

**Comment by bitbandit01** [comment]
Adding a comment to your post as I found it when struggling to use pagination.  You need to make sure to set the API version to one that accepts cursor-based pagination in order to get the `page` variable to populate.  Then you can loop through the resource using the provided `NextPageOptions`.

      client := goshopify.NewClient(app, store.StoreID, "", goshopify.WithVersion("2019-10"))

	// resource gets modified when calling Get
	resource, page, err := client.Product.ListWithPagination(nil)
	if err != nil {
		log.Println(err)
	}

	//Paginate through the results by checking for page.NextPageOptions
	for page.NextPageOptions != nil {
		opts := goshopify.ProductListOptions{
			ListOptions: goshopify.ListOptions{
				PageInfo: page.NextPageOptions.PageInfo,
			},
		}
		var additional []goshopify.Product
		additional, page, err = client.Product.ListWithPagination(opts)
		if err != nil {
			log.Println(err)
		}
		resource = append(resource, additional...)
	}
