### ISSUE TITLE
Support PriceRule resource

### ISSUE THREAD

**Issue by kogai** [bold-commerce/go-shopify#112]
Hi all ✋ 
I'm very enjoying to use go-shopify.

By the way, is there any plan to support the [PriceRule resource](https://shopify.dev/docs/admin-api/rest/reference/discounts/pricerule?api[version]=2020-07
) ❓

The search results for this repository indicate that the implementation of PriceRule was proposed once in #59.
(But it seems closed and didn't incorporate into the codebase. 😢 )

So, is there any plan to support the PriceRule resource or would you let me support it?

🙏

**Comment by kogai** [comment]
Can someone please answer this Issue ❓ 
I'm prepared to make a patch.

**Comment by gordcurrie** [comment]
Hi @kogai,
Sorry for the slow response. We generally add support for features as required by developers. If there is a specific feature that you require support for, we haven't added that feature yet, and you have the resources available, I would strongly encourage you to create a PR for the functionality and we would review and merge that into the code base. If you have any follow up questions or I can assist you in any way, please don't hesitate to reach out.
Gord

**Comment by kogai** [comment]
Hi @gordcurrie ,
Good to hear it! I'll create PR soon 🙏
