### ISSUE TITLE
Fulfillment	Receipt       is an array not object 

### ISSUE THREAD

**Issue by chenyangguang** [bold-commerce/go-shopify#128]
Fulfillment	Receipt       is an array not object

**Comment by joshsimard** [comment]
Care to elaborate? I'm seeing it as a struct here: https://github.com/bold-commerce/go-shopify/blob/e292691ac3de5a5cbd665ef5c46e09e27b1a83d2/fulfillment.go#L65

Also an object in the Shopify API: https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/fulfillment?api%5Bversion%5D=2020-01

Was there a different location in the code that you are referencing? Could you please provide more info? Thanks
