### ISSUE TITLE
Add a new WithClient option

### ISSUE THREAD

**Issue by fidel-ruiz** [bold-commerce/go-shopify#129]
Adding an option `WithClient`  that will allow to add custom configuration for the http client for example override the transport to add monitoring.

I'm willing to open an PR, if it's decided to move forward with this idea.

**Comment by luthermonson** [comment]
should be super easy, you should just add the PR

**Comment by ysurtayev-bold** [comment]
yep, this is good idea
I would prefer to include HTTP in its name (like `WithHTTPClient`) to make sure there is no confusion with other clients.

Please open a PR for it
