### ISSUE TITLE
Unable to specify PriceRule prerequisites using existing models.

### ISSUE THREAD

**Issue by BoldBrandonM** [bold-commerce/go-shopify#143]
While working with the PriceRules API client exposed by this package, I noticed that we are currently unable to specify PriceRule prerequisites (minimum purchase eligibility, minimum quantity eligibility, maximum shipping eligibility, etc)

This is a blocker for some work of ours, but would also pose a breaking change due to the rename of the types.

I've opened two PRs to illustrate some options and capture any pointed discussion, anything more general can be captured here in the comments.

Relevant PRs: 
https://github.com/bold-commerce/go-shopify/pull/142
#144

**Comment by gcfresh** [comment]
Not an ideal solution, but a workaround would be to use the client `NewRequest` and build a custom request to support the missing functionality.

**Comment by BoldBrandonM** [comment]
I agree, that could at least unblock us if this issue stays open for some time. Unfortunately that solution adds more tech debt to our side each time we do it.
