### ISSUE TITLE
Is this project still actively maintained?

### ISSUE THREAD

**Issue by catalogplus** [bold-commerce/go-shopify#173]
Hi,
It looks like most Shopify changes are not being added. Is this being actively maintained?
Thanks

**Comment by lukecyca** [comment]
I think most of us are maintaining our own forks, pulling in the various pull requests that this project has had open for quite some time.

**Comment by oliver006** [comment]
I've been maintaining my own fork on and off for a while but that's not great for obvious reasons.

I'd be happy to step up and help with maintaining this repo (at least review incoming PRs and keep things moving). I still actively use this library and and [contributed to it before.](https://github.com/bold-commerce/go-shopify/search?q=oliver006&type=issues)

cc'ing some of the previous PR reviewers and Bold org members  @BoldBrandonM @gordcurrie  @ysurtayev-bold @tysonkroeker @Natewich  to see what they think.

**Comment by gordcurrie** [comment]
I'm sorry folks I'm no longer with Bold so I can't speak to the activity of the maintainer group. They have an amazing group of Engineers but I'm sure they might be interested in getting some help maintaining the repo and encouraging community participation. I know their [developer portal](https://developer.boldcommerce.com/default/) has a contact us link it might be worth trying their if not getting any traction here.

**Comment by davemacaulay** [comment]
@oliver006 I'd love to chat more about this repository and your offer to help maintain it, could you reach out to me via email? `dave.macaulay@boldcommerce.com`.

**Comment by davemacaulay** [comment]
I've spoken to @oliver006 and we're going to look to move forward with him helping maintain this repository for everyone!

We will have more details to follow. Thanks for reaching out Oliver!

**Comment by oliver006** [comment]
A big thank you to Dave and everyone else from Bold Commerce that helped with getting me added as a maintainer.
There's a bit of a backlog but I'll start with reviewing and merging PRs in this repo as soon as possible.

**Comment by oliver006** [comment]
> Is this being actively maintained?

Yes!
I finally got through reviewing all the outstanding and will cut a new release tomorrow.

Going forward, I'll be available to review new PRs to keep things moving.

**Comment by oliver006** [comment]
Released https://github.com/bold-commerce/go-shopify/releases/tag/v3.13.0 - we're back in business.
