### ISSUE TITLE
Unable to use Metafields on 2021-07

### ISSUE THREAD

**Issue by BoldBrandonM** [bold-commerce/go-shopify#175]
While working with the Metafields API cleitn exposed by this package, I noticed that we're currently unable to work with Metafields on Shopify version 2021-07 since there was a breaking change to the model.

This is a blocker for some work of ours, but the change to this library can be non-breaking and transparently support both the old and new approaches.

**Comment by BoldBrandonM** [comment]
Created a PR to add support for this new field and indicate the old one will be deprecated going forward.

https://github.com/bold-commerce/go-shopify/pull/176

**Comment by gordcurrie** [comment]
🥳 great to see this library still actively maintained. 👍
