### ISSUE TITLE
Feature Request: Order Cancellation + Order Close

### ISSUE THREAD

**Issue by Krajiyah** [bold-commerce/go-shopify#181]
Admin REST APIs that would be beneficial to implement:
1. [Order Cancellation](https://shopify.dev/api/admin-rest/2022-04/resources/order#post-orders-order-id-cancel)
2. [Order Close](https://shopify.dev/api/admin-rest/2022-04/resources/order#post-orders-order-id-close)

Would be nice to see following methods as a result:
```golang
client := goshopify.NewClient(app, tenant, token)

cancelInput := goshopify.OrderCancelInput{ 
  OrderID: 1, // shopify id of order
  // rest of fields are optional fields documented in request parameters section of docs
}
if err := client.Order.Cancel(cancelInput); err != nil {
  // handle error
}

closeInput := goshopify.OrderCloseInput{
  OrderID: 1, // shopify id of order
  // rest of fields are optional fields documented in request parameters section of docs
}
if err := client.Order.Close(closeInput); err != nil {
  // handle error
}
```

Thoughts?

**Comment by oliver006** [comment]
https://github.com/bold-commerce/go-shopify/pull/103 added Cancel() and Close() - closing
