### ISSUE TITLE
InventoryQuantity is omitempty so no zero value can be sent

### ISSUE THREAD

**Issue by stefankahr** [bold-commerce/go-shopify#182]
currenty in variants.go the field InventoryQuantity is marked as "omitempty". Zero is an empty value in go so this field would not be sent to shopify. so you are not able to sent zero values.

**Comment by oliver006** [comment]
Sounds like we should make this a `int*` so it can be null (and ignored) or set to zero ?

**Comment by amit-evermile** [comment]
It's the same for the active field in CarrierResource, cannot set to false

**Comment by oliver006** [comment]
[v4.0.0](https://github.com/bold-commerce/go-shopify/releases/tag/v4.0.0) was released - this should be fixed.
