### ISSUE TITLE
gopkg.in/jarcoal/httpmock.v1: no matching versions for query "latest"

### ISSUE THREAD

**Issue by michael-bc** [bold-commerce/go-shopify#184]
When I try to run `go mod tidy` I get an error:

```
github.com/bold-commerce/go-shopify tested by
github.com/bold-commerce/go-shopify.test imports
gopkg.in/jarcoal/httpmock.v1: no matching versions for query "latest"
```

Do you have any suggestion for resolving this issue?

**Comment by pure-commerce** [comment]
Did you manage to get this fixed?

**Comment by pure-commerce** [comment]
I was able to get my program to compile by updating to the latest Go install. Go mod tidy still returns that error but atleast I can compile.

**Comment by shrumm** [comment]
make sure you're on the latest v3 version: `go get github.com/bold-commerce/go-shopify/v3`

there's a [PR](https://github.com/bold-commerce/go-shopify/pull/183) to update the documentation to reflect this, but it hasn't been merged yet.

**Comment by whiskerside** [comment]
Change the import to `github.com/bold-commerce/go-shopify/v3` then run `go mod tidy` to resolve it.
