### ISSUE TITLE
Fulfillment endpoints are deprecated, need support for FulfillmentOrder

### ISSUE THREAD

**Issue by nayakmanju** [bold-commerce/go-shopify#197]
As per release 2022-07, the fulfillment endpoints have been removed from the rest admin api.
https://shopify.dev/docs/api/release-notes/2022-07#fulfillment-endpoints-removed-from-the-rest-admin-api
Are there any pans to update this repo with the alternatives?

**Comment by oliver006** [comment]
Thanks for raising the issue. There are no plans yet but help is appreciated.

To address this we need to add support for FulfillmentOrder:  https://shopify.dev/docs/api/admin-rest/2023-01/resources/fulfillmentorder

**Comment by krisatverbidio** [comment]
I have begun working on this. Base implementation is complete, and am working on tests and testing. Will submit a PR when ready.

**Comment by oliver006** [comment]
Thanks @krisatverbidio !

**Comment by c9845** [comment]
Hi all, this became a bit more urgent since as of today (I assume since 1 July) the old implementation is now broken and the `CreateFulfullment()` func now returns an error.  @krisatverbidio, do you have any progress to share and/or test?

**Comment by krisatverbidio** [comment]
I haven't had time to complete the tests. Functionality is complete, but tests are not. I'll see if I can bump this up on my priority list over the next few days.

**Comment by drewdgilmore** [comment]
@krisatverbidio any chance you can push the "functionality" to a new branch so its available?

**Comment by krisatverbidio** [comment]
Sure, see my fork/branch here:
https://github.com/krisatverbidio/go-shopify/tree/issue-197-support-fulfillment-order

**Comment by drewdgilmore** [comment]
@krisatverbidio thanks!

**Comment by oliver006** [comment]
@krisatverbidio - want to open a PR and maybe we can figure out a way to add the missing tests later?

**Comment by krisatverbidio** [comment]
Sure, I’ll do that tomorrow.

**Comment by krisatverbidio** [comment]
@oliver006 Created PR #216 as noted above. A few of the final tests are stubbed out. My day job has been too demanding for me to be able to complete those, but the implementation should be there in the rest of its entirety.

**Comment by Viktoop** [comment]
Is there need to somehow link the [Order Fulfillment service](https://github.com/bold-commerce/go-shopify/blob/933070bd18d903297fbee9deb55c3cba87be133d/order.go#L33C16-L33C16)  with the new written FulfillmentOrder service from PR #216 , or is it not needed ?
