### ISSUE TITLE
How to get 'risks' api response?

### ISSUE THREAD

**Issue by astsiatsko** [bold-commerce/go-shopify#204]
I need to have order risk api available in the library
https://shopify.dev/docs/api/admin-rest/2022-04/resources/order-risk#get-orders-order-id-risks
Is it possible at the moment?

**Comment by oliver006** [comment]
The Order Risk resource has not been added yet. Could be a good first PR if someone is interested.

**Comment by oliver006** [comment]
https://github.com/bold-commerce/go-shopify/pull/254 added order risk endpoint support - closing.
