### ISSUE TITLE
Add HS Code info to InventoryItem

### ISSUE THREAD

**Issue by c9845** [bold-commerce/go-shopify#212]
The [`InventoryItem`](https://pkg.go.dev/github.com/bold-commerce/go-shopify#InventoryItem) type is missing a number of fields to handle HS code information.  Specifically, `country_code_of_origin`, `country_harmonized_system_codes`, `harmonized_system_code`, and `province_code_of_origin`.  

Not sure if these were omitted for a specific reason or added to Shopify's API after this package was built out.  Can these be added?

See https://shopify.dev/docs/api/admin-rest/2023-04/resources/inventoryitem#resource-object for the list of fields available for an InventoryItem.

**Comment by oliver006** [comment]
Thanks for raising this. they were not omitted for a specific reason, probably cause they just got added later or the original author didn't need them.

This definitely could use some help, open a PR if you have a minute and I'll review and merge it asap.

**Comment by oliver006** [comment]
I think this got addressed by #213
