### ISSUE TITLE
The required line_items_by_fulfillment_order field is missing error.

### ISSUE THREAD

**Issue by mbobrovskyi** [bold-commerce/go-shopify#219]
When I'm trying to create fulfillment I got error `The required line_items_by_fulfillment_order field is missing error.` with status 400. 

As I can see on documentation it was change Fulfillment model for create (https://shopify.dev/docs/api/admin-rest/2023-01/resources/fulfillment#post-fulfillments-fulfillment-id-update-tracking).

**Comment by oliver006** [comment]
You're right, this is currently missing and needs some updating.
I'm a bit tight with time but I can review a PR if you (or anyone else!) sends one over.

**Comment by oliver006** [comment]
I think this was fixed by https://github.com/bold-commerce/go-shopify/pull/241

**Comment by oliver006** [comment]
https://github.com/bold-commerce/go-shopify/blob/master/fulfillment.go#L63
