### ISSUE TITLE
List Customer Addresses doesn't use pagination - just always returns the first page (and no pagination information)

### ISSUE THREAD

**Issue by Will-Atherton** [bold-commerce/go-shopify#230]
The api call to List customer addresses uses pagination in shopify.
The function in go-shopify, List in customeraddresses.go (I think) just returns a list of addresses, with no pagination information
It will always return the first page

**Comment by bbtb1982** [comment]
Here is the reference in the docs showing the customer address allows for headers for pagination similar to other endpoints.  

[shopify get-customer-addresses](https://shopify.dev/docs/api/admin-rest/2024-01/resources/customer-address#get-customers-customer-id-addresses?limit=1)

**Comment by oliver006** [comment]
https://github.com/bold-commerce/go-shopify/pull/282 added a ListAll() call to all resources - try if that helps.
