### ISSUE TITLE
not support custom header, such as X-Shopify-Api-Features

### ISSUE THREAD

**Issue by xdlbdy** [bold-commerce/go-shopify#248]
[variant](https://shopify.dev/docs/api/admin-rest/2023-10/resources/product-variant) response property `presentment_prices`, but  it requires the header `'X-Shopify-Api-Features': 'include-presentment-prices'`
 
<img width="691" alt="image" src="https://github.com/bold-commerce/go-shopify/assets/4382157/603eaef6-d21d-4285-be1b-3a15e4f05105">

**Comment by oliver006** [comment]
I _think_ you can try adding these headers but passing your own http client but otherwise there's currently no support for passing custom headers.
