### ISSUE TITLE
v3 code has no Graphql Service exists

### ISSUE THREAD

**Issue by khanakia** [bold-commerce/go-shopify#251]
I want to make a Graphql Request and I can see the library supports the graphql request as here https://github.com/bold-commerce/go-shopify/blob/25ac74adf2a23bd53db57d8c22ce0a217cdc34b6/goshopify.go#L127

But when I use the latest v3 `import "github.com/bold-commerce/go-shopify/v3"` as per docs and check the code `vendor/github.com/bold-commerce/go-shopify/v3/goshopify.go` it's different than the GitHub repo and there is no `Graphql` Property exists.

**Comment by oliver006** [comment]
Oooooops, it's been a while since the last releae.
I just cut https://github.com/bold-commerce/go-shopify/releases/tag/v3.16.0 - try that one and let me know if it works.
