### ISSUE TITLE
ProductListOptions are missing some fields

### ISSUE THREAD

**Issue by shuqingzai** [bold-commerce/go-shopify#253]
See: https://shopify.dev/docs/api/admin-rest/2023-10/resources/product#get-products?ids=632910392,921728736

https://github.com/bold-commerce/go-shopify/blob/e40406f4c4b9545419cd98363896b707f0fa15e3/product.go#L90

missing `Title`

**Comment by oliver006** [comment]
Good catch, that's missing. Can you open a PR that adds it? Thanks!
