### ISSUE TITLE
RecurringApplicationCharge has no field 'currency'

### ISSUE THREAD

**Issue by OliverAAAAA** [bold-commerce/go-shopify#262]
Official documents  has field 'currency' = "USD" behind

{
  "activated_on": null,
  "billing_on": null,
  "cancelled_on": null,
  "capped_amount": "100",
  "confirmation_url": "https://jsmith.myshopify.com/admin/charges/confirm_recurring_application_charge?id=654381177&amp;signature=BAhpBHkQASc%3D--374c02da2ea0371b23f40781b8a6d5f4a520e77b",
  "created_at": "2013-06-27T08:48:27-04:00",
  "id": 675931192,
  "name": "Super Duper Expensive action",
  "price": "100.00",
  "return_url": "http://super-duper.shopifyapps.com",
  "status": "accepted",
  "terms": "$1 for 1000 emails",
  "test": null,
  "trial_days": 0,
  "trial_ends_on": null,
  "updated_at": "2013-06-27T08:48:27-04:00",
  "currency": "USD"
}

**Comment by oliver006** [comment]
Good catch, that's missing. Can you open a PR that adds it? Thanks!

**Comment by OliverAAAAA** [comment]
yeah, i  have opened a PR , please review it !

**Comment by oliver006** [comment]
Done - thanks!
