### ISSUE TITLE
Image Upload Fields Have Lost Support

### ISSUE THREAD

**Issue by MarkFullerInflxr** [bold-commerce/go-shopify#263]
The Image upload has completely lost support for `imageSrc` and `imageId` for product variants. I will try to make a PR today to fix. 

https://shopify.dev/docs/api/release-notes/2024-01#field-removals-on-productvariantinput

**Comment by oliver006** [comment]
What happened? Does this need fixing or is it working?

**Comment by MarkFullerInflxr** [comment]
It was my misunderstanding, we are experiencing an odd error coming from shopify on image upload and I believed that to be the root cause. But that documentation for the graphql api not the rest one. In the meantime we have figured out how to circumvent the issue.
