### ISSUE TITLE
Possible addition of bson metafields in the model structs

### ISSUE THREAD

**Issue by kushthedude** [bold-commerce/go-shopify#283]
The library doesn't add bson metafields in the Struct for all shopify objects which results in data to get messed up if you put in mongo or try to retrieve back from it.

I can look into adding them; if community agrees that this may be implemented.

**Comment by kushthedude** [comment]
@oliver006

**Comment by oliver006** [comment]
This library is for interactions with the Shopify REST API. I'd prefer to not add unrelated bloat to the library, if you want to store objects in Mongo DB then please implement proper serialization on your end.
