### ISSUE TITLE
Add alt tag to Product Image

### ISSUE THREAD

**Issue by ash-mank** [bold-commerce/go-shopify#285]
According to https://shopify.dev/docs/api/admin-rest/2024-04/resources/product-image, alt column is added to product image structure. Request to expose it as part of Image struct.

**Comment by ash-mank** [comment]
<img width="530" alt="Screenshot 2024-04-29 at 6 59 11 PM" src="https://github.com/bold-commerce/go-shopify/assets/168443625/babc14c9-bcbe-4ccd-b64a-98c1ed494813">

**Comment by ash-mank** [comment]
@oliver006 This seems to be a very small change, just an addition of a member variable in Image struct. Can you please help prioritize it?

**Comment by oliver006** [comment]
Thanks for the nudge.
I currently don't have time to handle this myself but can review and merge a PR if you submit one.
