### ISSUE TITLE
Removal of the delivery_category field on order shipping lines

### ISSUE THREAD

**Issue by raghavendramendon** [bold-commerce/go-shopify#293]
As of 2023-07, shopify deprecating the order shipping line delivery_category property. The property has not been in use since 2020-06-12 and will no longer be present.
FYR -> https://shopify.dev/changelog/removal-of-the-delivery_category-field-on-order-shipping-lines

**Comment by oliver006** [comment]
See #292

**Comment by raghavendramendon** [comment]
Thank you!

**Comment by raghavendramendon** [comment]
I'm currently using go get -u github.com/bold-commerce/go-shopify to update the package, but I'm unable to see the recent code changes. Can anyone help me update the package to include the latest changes?
