### ISSUE TITLE
Unable to update the package with recent code change

### ISSUE THREAD

**Issue by raghavendramendon** [bold-commerce/go-shopify#294]
I'm currently using go get -u github.com/bold-commerce/go-shopify to update the package, but I'm unable to see the recent code changes. Can anyone help me update the package to include the latest changes?

**Comment by oliver006** [comment]
Let me cut a new release and you should be able to get the latest changes via `go get`, gimme a few.

**Comment by raghavendramendon** [comment]
Thank you @oliver006 !

**Comment by oliver006** [comment]
Released https://github.com/bold-commerce/go-shopify/releases/tag/v4.4.0
