### ISSUE TITLE
[BUG] Many enums are not exported and are not available externally.

### ISSUE THREAD

**Issue by shuqingzai** [bold-commerce/go-shopify#303]
See: #264 

1. Order Enums

- https://github.com/bold-commerce/go-shopify/blob/e0f9e0d4dfc7654a6c9aa310fafe304de2259b3e/order.go#L46
- https://github.com/bold-commerce/go-shopify/blob/e0f9e0d4dfc7654a6c9aa310fafe304de2259b3e/order.go#L63
- more...

2. Variant Enums

- https://github.com/bold-commerce/go-shopify/blob/e0f9e0d4dfc7654a6c9aa310fafe304de2259b3e/variant.go#L37

There may be others, I haven't checked carefully

**Comment by oliver006** [comment]
Yeah, I think we could/should export them.
Happy to review / merge a PR.
