### ISSUE TITLE
Missing total_tip_received column to the order struct

### ISSUE THREAD

**Issue by khanakia** [bold-commerce/go-shopify#307]
Struct is missing the below field

`github.com/bold-commerce/go-shopify/v4@v4.6.0/order.go`
```go
type Order struct {
  TotalTipReceived   string      `json:"total_tip_received,omitempty"`
}
```

**Comment by oliver006** [comment]
Thanks for raising the issue. Can you please submit a PR to add it? Thanks!

**Comment by khanakia** [comment]
I have created a pull request https://github.com/bold-commerce/go-shopify/pull/308
