### ISSUE TITLE
Does go-shopify need work with shopify.com ?

### ISSUE THREAD

**Issue by goodforever** [bold-commerce/go-shopify#39]
Does go-shopify need work with shopify.com service ?

**Comment by andrewhoff** [comment]
Hey @goodforever! I'm not quite sure I understand the question. Could you elaborate?

**Comment by goodforever** [comment]
@andrewhoff Need the go-shopify use service of shopify.com as backend server ?

**Comment by andrewhoff** [comment]
Hey @goodforever! go-shopify is an api client library for shopify stores, so you will need a shopify app, could be a sandbox one to point the go-shopify library at. If you're concerned about needing a shopify app to run go-shopify's tests, that is covered by a http mock library in the tests. Hope that helps!

**Comment by andrewhoff** [comment]
Hey @goodforever! I hope any confusion has been cleared up for you, I'm going to close this ticket for now.
