### ISSUE TITLE
Incorrect precision on Id's, int64 != 32 digits

### ISSUE THREAD

**Issue by thecaddy** [bold-commerce/go-shopify#62]
From the shopify docs:
```
A unique numeric identifier, of up to 32 digits, for the product. 
Each id is unique across the Shopify system.
No two products will have the same id, even if they're from different shops. 
```

largest int64 (8 bytes)
9223372036854775807 = 19 digits

if its uint64, you can get to 20 digits

It is probably better to represent the Id's as strings or some custom type.

**Comment by rickywiens** [comment]
Hey @thecaddy, thanks for posting. Do you have a link to the documentation for that? We haven't seen any IDs come back with Shopify with that many digits yet - but you're right it'd be better to be correct.

**Comment by thecaddy** [comment]
https://help.shopify.com/en/api/reference/products/product

The blurb posted above is from the product model definition.  I'm working with Orders as well and it appears Shopify has inconsistent/less descriptive definitions of how the Id is stored in their system throughout their docs.

I'm personally storing 32 char strings based on their product model for all of their id's.  I fear the pain of one of their id's potentially hitting 21 digits and having to do a refactor/migration.  Call me paranoid.  /shrug

From the Orders api:
```
The ID of the order, used for API purposes. This is different from the order_number property, which is the ID used by the shop owner and customer.' 
```

**Comment by rickywiens** [comment]
I just reached out to their developer support and I got this response:

> Hey Ricky.
> 
> Thanks a million for the report.
> 
> This definitely looks to have been made in error. We store these as BIGINT(20), or 64 bit unsigned integers, which reaches up to 20 digits, so 32 shouldn't be possible. I'm going to go through and update documentation to clarify this simply as a 64 bit unsigned integer.

Looks like internally it's represented as a BIGINT - which will always fit exactly into a int64.

**Comment by thecaddy** [comment]
Great thanks @rickywiens for doing the heavy lifting and confirming! 👍
