### ISSUE TITLE
The page filter has been removed. Please use cursor-based pagination instead.

### ISSUE THREAD

**Issue by thecaddy** [bold-commerce/go-shopify#64]
Received an email from Shopify that paging is deprecated and to use the cursor.  April 1, 2020 looks to be the cutoff so it's still a way out.  Will cursor-based paging be supported?

https://help.shopify.com/en/api/guides/paginated-rest-results?utm_source=exacttarget&utm_medium=email&utm_campaign=api_deprecation_notice_1908

**Comment by brendankay** [comment]
I've had a go at adding support [here](https://github.com/bold-commerce/go-shopify/pull/73)

**Comment by oliver006** [comment]
I think this was closed by #84
