### ISSUE TITLE
IDs should use int64 instead of int

### ISSUE THREAD

**Issue by andrewhoff** [bold-commerce/go-shopify#7]
_From @orian on June 8, 2018 6:27_

For some objects Shopify is using a global ID space and recently the threshold of 2^31-1 has been exceeded.

The Go's int size is at least 32 bits, but not guaranteed to be bigger (e.g. `int64`).

I propose to switch all `int` ids into `int64`.

_Copied from original issue: getconversio/go-shopify#92_

**Comment by andrewhoff** [comment]
_From @dlebech on June 11, 2018 20:9_

Thanks for bringing this up. This was on my mind as well when I initially created the library. The reason I went with `int` was simplicity and the fact that I don't expect anyone to run 32 bit Go servers (It is my understanding that if a 64-bit processor is available, `int` will always be a 64 bit integer.) Of course, this could be the wrong assumption, and I would be curious to know what the best practice is currently (I'm a bit out of touch 🙂 ) *and* whether changing all `int`s to `int64` will actually be a breaking change in the library. `int` and `int64` are different types, after all 🤔

**Comment by andrewhoff** [comment]
_From @orian on June 12, 2018 10:59_

It would break a library's API. It would make sense to version a library (add a tag) and introduce a change in version 2.
As far as my experience if the numbers are expected to be > 32 bits, the only way to guarantee that software does not break is to use int64.
I can imagine a situation when some magic is introduce in processors so smaller numbers are processed faster and Go team decides to change the size of int (as the language spec allows the compiler to choose int size).

**Comment by andrewhoff** [comment]
_From @dlebech on June 14, 2018 19:10_

It's a good point about the language spec. I honestly don't know what the best way forward is here. Perhaps we can let this brew for a few days so the community (if they are listening) can voice their support or concerns.

I've almost always used Go vendoring, so a change like this would only break my work when I updated the library locally but not on a production server, but I'm not sure this is 100% ubiquitous in the community yet (?), and if it isn't, I'm not sure that just tagging something as "v2" will do any good?

**Comment by andrewhoff** [comment]
_From @nelz9999 on June 25, 2018 20:6_

SemVer the releases!

**Comment by dougyss4** [comment]
I've only just begun using this project, and until running into this issue it's been great to work with, however we run into a number of issues with this.   Are there any plans to address it, or do we need to fork and work on this on our own?  Alternatively, is it known if there is already a fork out there which has addressed this issue?

**Comment by rickywiens** [comment]
If you had a PR to implement this change we would work with you to merge it in. So far this hasn't come up as an issue in our implementations of this, but it is something that we do want to address.

I'm not aware of any forks that address this specific issue.

**Comment by dougyss4** [comment]
Ok, we’ll get started on it here, at least as far as the entities we deal with, which is primarily the product catalog side of things.   That’s our initial requirement in any case, we’ll see where it goes from there I guess.

Thanks

On Mar 21, 2019, at 10:12, Ricky <notifications@github.com<mailto:notifications@github.com>> wrote:


If you had a PR to implement this change we would work with you to merge it in. So far this hasn't come up as an issue in our implementations of this, but it is something that we do want to address.

I'm not aware of any forks that address this specific issue.

**Comment by rickywiens** [comment]
This has been resolved in #46
