### ISSUE TITLE
requested_fulfillment_service_id should be nullable int instead of string?

### ISSUE THREAD

**Issue by umsu2** [bold-commerce/go-shopify#71]
i have noticed `requested_fulfillment_service_id` having `int` or null value but not a string value. 
is there any indication/instance that this field is string instead?

**Comment by BoldBrandonM** [comment]
Just checking in, should this issue be closed per the commit pushed above? Based on the code change it appears that the custom unmarshaller explicitly handles for strings instead of ints.
