### ISSUE TITLE
SinceID as Zero and omitempty

### ISSUE THREAD

**Issue by luthermonson** [bold-commerce/go-shopify#89]
**Problem**
SinceId is an int64 but the API documentation tells you to pass since_id=0 to work with paginated results. I found a problem in the smartcollections end point where it sorts by alpha title on default so in order to force an id sort you have to to use since_id=0 properly and have to initialize that param to force the id sort. With omitempty on SinceID the marshaler will consider this empty and not send the param even if you explicitly set it to int64(0) since obviously omitempty considers zero an empty int64 type. Also, if you don't set the param the struct will still initialize with zero and you dont want to pass since_id=0 ALL the time so you can't just remove omitempty.

**Workaround**
Initialize SinceID as int64(1) as it is basically the same thing for all intents and purposes but is not technically not what the api documents as the proper method and could trip up a developer.

**Fix?**
Possibly just document as a limitation on the struct field

**Comment by oliver006** [comment]
For scenarios where you need control over including e.g. an int64 field in your json output but still need it to be zero, the best way I've seen is making the int a reference in the struct and then set it to nil if you want to omit it or `= &zero` (where `zero := 0`) if you want to include a zero value.

**Comment by luthermonson** [comment]
Ya that is how I'd get around that too is add a nil option. Changing it now would break existing code so if this route was taken it should probably be included in a new major version

**Comment by oliver006** [comment]
🤷‍♀ - you could make the backwards incompatible change and release it as a new major version. Should be an easy change for callers as long as it provides a convenience function `Get/Set Id()` or similar that sets/returns 0 in case the struct value is nil.

**Comment by oliver006** [comment]
Addressing this in #258 (by making SinceId a *uint64 )

**Comment by oliver006** [comment]
[v4.0.0](https://github.com/bold-commerce/go-shopify/releases/tag/v4.0.0) was released - this should be fixed.
