### ISSUE TITLE
Pagination parsing regex is incorrect

### ISSUE THREAD

**Issue by MathiasGr** [bold-commerce/go-shopify#91]
I was trying out product pagination parsing, and ended up having to change the link parsing regex for the code to work:

Here's the regex in your code:

https://github.com/bold-commerce/go-shopify/blob/fa02f8527c483bbc6ab25aa0b8d6428611001bb0/product.go#L17

And the example from the Shopify docs:
```
#...
Link: "<https://{shop}.myshopify.com/admin/api/2019-07/products.json?page_info=hijgklmn&limit=3>; rel=next"
#...
```

The quotes around `(previous|next)` are nowhere to be seen in the docs, so either the Shopify docs are wrong (I haven't tried against their live API yet), or the regex is invalid. Just removing the quote seems to make my tests pass against the Shopify docs example.

**Comment by luthermonson** [comment]
@MathiasGr Docs are wrong, the api does in fact return the quotes and this works fine. Below is the contents of `linkHeader` passed to `extractPagination` from my quick test to confirm while refactoring the pagination code a bit.

```
<https://redacted.myshopify.com/admin/api/2020-04/products.json?limit=5&page_info=eyJkaXJlY3Rpb24iOiJwcmV2IiwibGFzdF9pZCI6NDMyMzYyODY3NSwibGFzdF92YWx1ZSI6IkEtRW5nbGFuZCAtIEJyaWFyd29vZCJ9>; rel="previous", <https://redacted/admin/api/2020-04/products.json?limit=5&page_info=eyJkaXJlY3Rpb24iOiJuZXh0IiwibGFzdF9pZCI6Mzg3ODkzMzg1NjMzOSwibGFzdF92YWx1ZSI6IkEtRW5nbGFuZCAtIENhcm5hYnkgU3RyZWV0In0>; rel="next"
```

can you post the responses you were getting showing no quotes?
